# Generated by Django 5.0.6 on 2024-08-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='gender_type',
            new_name='gender',
        ),
    ]
