# Generated by Django 5.0.6 on 2024-08-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_gender_type_userbankaccount_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
